name: MSBuild

on:
  push:
    branches: [ "msbuild" ]
  pull_request:
    branches: [ "msbuild" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mono:latest

    steps:
    - uses: actions/checkout@v3

    - name: Set workspace permissions
      run: chmod 777 -R "$GITHUB_WORKSPACE"

    - name: Build
      run: |
        apt-get update
        apt -y install mono-complete
        cd $GITHUB_WORKSPACE
        ./compile.sh Release x86
        cd $GITHUB_WORKSPACE/build
        mkbundle --deps Tinke.exe -o Tinke --machine-config /etc/mono/4.5/machine.config --i18n all
      shell: bash

    - uses: actions/upload-artifact@master
      with:
        name: TinkeDSi-nightly-x86
        path: build
