# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "msbuild" ]
  pull_request:
    branches: [ "msbuild" ]

env:
  Solution_Name: Tinke.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd /home/runner/work/TinkeDSi/TinkeDSi && compile.sh Release x86

    - uses: actions/upload-artifact@master
      with:
        name: TinkeDSi-nightly-x86
        path: build
