name: MSBuild

on:
  push:
    branches: [ "msbuild" ]
  pull_request:
    branches: [ "msbuild" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mono:latest

    steps:
    - uses: actions/checkout@v3

    - name: Set workspace permissions
      run: chmod 777 -R "$GITHUB_WORKSPACE"

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        compile.sh Release x86

    - uses: actions/upload-artifact@master
      with:
        name: TinkeDSi-nightly-x86
        path: build
